// frontend/src/components/chat/AssistantMessage.tsx
import { useState } from 'react'
import { Message } from '@/types/chat'
import { BarChart2, Activity, Database, ChevronDown, ChevronUp, Check, Download } from 'lucide-react'
import dynamic from 'next/dynamic'

const Plot = dynamic(() => import('react-plotly.js'), { ssr: false })

export default function AssistantMessage({ message, onFollowup }: { message: Message, onFollowup: (q: string) => void }) {
  const [activePanel, setActivePanel] = useState<'chart' | 'data' | 'sql' | null>(null)

  const togglePanel = (panel: 'chart' | 'data' | 'sql') => {
    setActivePanel(activePanel === panel ? null : panel)
  }

  return (
    <div className="flex gap-4 mb-6 w-full">
      <div className="h-10 w-10 shrink-0 rounded-xl bg-brand-navy flex items-center justify-center text-brand-light font-bold text-xl shadow-sm border border-brand-primary/20">
        ◈
      </div>
      
      <div className="flex-1 space-y-3 min-w-0">
        {/* Status Bar */}
        {(message.status !== 'pending' || message.domain) && (
          <div className="inline-flex items-center gap-2 bg-brand-surface border border-brand-primary/20 text-brand-navy px-3 py-1.5 rounded-lg text-xs font-medium">
            {message.domain === 'asset' ? <Activity size={14} /> : <BarChart2 size={14} />}
            <span className="capitalize">{message.domain || 'Analytics'}</span>
            {message.rowCount !== undefined && (
              <>
                <span className="text-brand-primary/40">•</span>
                <span>{message.rowCount} rows processed</span>
              </>
            )}
          </div>
        )}

        {/* Typing indicator */}
        {message.status === 'pending' && !message.content && (
          <div className="flex gap-1 items-center h-6 px-2">
            <div className="w-2 h-2 rounded-full bg-brand-primary animate-bounce" style={{ animationDelay: '0ms' }} />
            <div className="w-2 h-2 rounded-full bg-brand-primary animate-bounce" style={{ animationDelay: '150ms' }} />
            <div className="w-2 h-2 rounded-full bg-brand-primary animate-bounce" style={{ animationDelay: '300ms' }} />
          </div>
        )}

        {/* Main Content */}
        {message.content && (
          <div className="prose prose-sm max-w-none text-gray-800 leading-relaxed">
            {message.content}
          </div>
        )}

        {/* Collapsible Panels */}
        {(message.sql || message.data || message.chartSpec) && (
          <div className="flex flex-wrap gap-2 mt-4">
            {message.chartSpec && (
              <button 
                onClick={() => togglePanel('chart')}
                className={`flex items-center gap-1.5 px-3 py-1.5 rounded-md text-sm font-medium transition-colors border ${activePanel === 'chart' ? 'bg-brand-primary text-white border-brand-primary' : 'bg-white text-gray-700 border-gray-200 hover:bg-gray-50'}`}
              >
                <BarChart2 size={16} /> Chart {activePanel === 'chart' ? <ChevronUp size={14} /> : <ChevronDown size={14} />}
              </button>
            )}
            
            {message.data && (
              <button 
                onClick={() => togglePanel('data')}
                className={`flex items-center gap-1.5 px-3 py-1.5 rounded-md text-sm font-medium transition-colors border ${activePanel === 'data' ? 'bg-brand-primary text-white border-brand-primary' : 'bg-white text-gray-700 border-gray-200 hover:bg-gray-50'}`}
              >
                <Database size={16} /> Data {activePanel === 'data' ? <ChevronUp size={14} /> : <ChevronDown size={14} />}
              </button>
            )}

            {message.sql && (
              <button 
                onClick={() => togglePanel('sql')}
                className={`flex items-center gap-1.5 px-3 py-1.5 rounded-md text-sm font-medium transition-colors border ${activePanel === 'sql' ? 'bg-brand-primary text-white border-brand-primary' : 'bg-white text-gray-700 border-gray-200 hover:bg-gray-50'}`}
              >
                SQL {activePanel === 'sql' ? <ChevronUp size={14} /> : <ChevronDown size={14} />}
              </button>
            )}
          </div>
        )}

        {/* Panel Content */}
        {activePanel === 'sql' && message.sql && (
          <div className="bg-gray-900 rounded-lg p-4 mt-2 overflow-x-auto border border-gray-800">
            <pre className="text-gray-300 text-sm font-mono whitespace-pre-wrap">{message.sql}</pre>
          </div>
        )}

        {activePanel === 'data' && message.data && message.data.length > 0 && (
          <div className="bg-white rounded-lg border border-gray-200 mt-2 overflow-hidden">
            <div className="overflow-x-auto max-h-[400px]">
              <table className="w-full text-sm text-left">
                <thead className="text-xs text-gray-500 uppercase bg-gray-50 sticky top-0">
                  <tr>
                    {Object.keys(message.data[0]).map(key => (
                      <th key={key} className="px-4 py-3 font-medium border-b border-gray-200 whitespace-nowrap">{key}</th>
                    ))}
                  </tr>
                </thead>
                <tbody className="divide-y divide-gray-100">
                  {message.data.slice(0, 100).map((row, i) => (
                    <tr key={i} className="hover:bg-gray-50 transition-colors">
                      {Object.values(row).map((val: any, j) => (
                        <td key={j} className="px-4 py-2.5 whitespace-nowrap text-gray-700">
                          {val === null ? <span className="text-gray-400 italic">null</span> : String(val)}
                        </td>
                      ))}
                    </tr>
                  ))}
                </tbody>
              </table>
            </div>
            {message.data.length > 100 && (
              <div className="bg-gray-50 p-2 text-center text-xs text-gray-500 border-t border-gray-200">
                Showing 100 of {message.data.length} rows
              </div>
            )}
          </div>
        )}

        {activePanel === 'chart' && message.chartSpec && message.data && (
          <div className="bg-white rounded-lg border border-gray-200 mt-2 p-4 min-h-[300px] flex items-center justify-center">
            <Plot
              data={[{
                type: message.chartSpec.active as any,
                x: message.data.map((d: any) => d[message.chartSpec!.recommendations[0]?.x] || d[Object.keys(d)[0]]),
                y: message.data.map((d: any) => d[message.chartSpec!.recommendations[0]?.y] || d[Object.keys(d)[1]]),
                marker: { color: '#28A5A0' },
              }]}
              layout={{ 
                autosize: true, 
                margin: { t: 20, r: 20, l: 40, b: 40 },
                paper_bgcolor: 'transparent',
                plot_bgcolor: 'transparent',
                font: { family: 'Inter, sans-serif' }
              }}
              useResizeHandler={true}
              className="w-full h-[400px]"
              config={{ displayModeBar: false, responsive: true }}
            />
          </div>
        )}

        {/* Follow-ups */}
        {message.followups && message.followups.length > 0 && (
          <div className="flex flex-wrap gap-2 mt-4 pt-2">
            {message.followups.map((f, i) => (
              <button
                key={i}
                onClick={() => onFollowup(f)}
                className="inline-flex items-center gap-1.5 px-3 py-1.5 rounded-full bg-brand-surface hover:bg-brand-light/20 text-brand-navy border border-brand-primary/20 text-xs font-medium transition-colors"
              >
                <span className="text-brand-primary">💡</span> {f}
              </button>
            ))}
          </div>
        )}
      </div>
    </div>
  )
}

// frontend-angular/src/app/features/chat/assistant-message/assistant-message.component.ts
import { Component, Input, Output, EventEmitter, ChangeDetectionStrategy } from '@angular/core';
import { CommonModule } from '@angular/common';
import { ChatMessage } from '../../../shared/models/chat.model';
import { SqlPanelComponent } from '../sql-panel/sql-panel.component';
import { DataTableComponent } from '../data-table/data-table.component';
import { ChartSelectorComponent } from '../chart-selector/chart-selector.component';
import { ExportService } from '../../../core/services/export.service';
import { LucideAngularModule } from 'lucide-angular';

@Component({
  selector: 'app-assistant-message',
  standalone: true,
  imports: [CommonModule, SqlPanelComponent, DataTableComponent, ChartSelectorComponent, LucideAngularModule],
  changeDetection: ChangeDetectionStrategy.OnPush,
  templateUrl: './assistant-message.component.html',
})
export class AssistantMessageComponent {
  @Input() message!: ChatMessage;
  @Input() originalQuestion: string = '';
  @Output() followupClick = new EventEmitter<string>();

  showChart = true;
  showData = false;
  showSql = false;
  showExportMenu = false;

  constructor(private exportSvc: ExportService) {}

  doExport(format: 'csv' | 'excel' | 'pdf') {
    if (this.originalQuestion) {
      this.exportSvc.export(this.originalQuestion, format);
    }
    this.showExportMenu = false;
  }
}

<div class="flex gap-3">
  <!-- TW Avatar -->
  <div class="w-8 h-8 rounded-xl bg-brand-navy text-white flex items-center
              justify-center text-xs font-bold flex-shrink-0 mt-0.5">
    TW
  </div>

  <div class="flex-1 max-w-2xl min-w-0">

    <!-- Typing indicator -->
    <div *ngIf="message.status === 'pending'" class="flex gap-1 py-2 items-center">
      <span class="w-2 h-2 bg-gray-300 rounded-full animate-bounce"></span>
      <span class="w-2 h-2 bg-gray-300 rounded-full animate-bounce [animation-delay:100ms]"></span>
      <span class="w-2 h-2 bg-gray-300 rounded-full animate-bounce [animation-delay:200ms]"></span>
    </div>

    <!-- Status badge and Dropdown menu -->
    <div *ngIf="message.domain && message.domain !== 'conversational'" class="flex items-center gap-2 mb-2">
      <div class="inline-flex items-center gap-1.5 bg-brand-surface text-brand-navy
                  text-xs px-3 py-1 rounded-full font-medium">
        <lucide-icon name="activity" class="w-3 h-3"></lucide-icon>
        <span>{{ message.domain | titlecase }} Analytics</span>
        <span *ngIf="message.rowCount !== undefined" class="text-brand-primary">
          · {{ message.rowCount }} rows
        </span>
      </div>

      <div class="relative" *ngIf="message.status === 'complete' && (message.data || message.sql || message.displaySections)">
        <button (click)="showMenu = !showMenu"
                class="hover:bg-gray-100 rounded-full p-1 text-gray-500 transition-colors focus:outline-none">
          <lucide-icon name="more-vertical" class="w-4 h-4"></lucide-icon>
        </button>
        
        <div *ngIf="showMenu" class="absolute left-0 top-full mt-1 bg-white border border-gray-200 shadow-lg rounded-lg py-1 z-50 min-w-[120px]">
          <button *ngIf="message.data || message.displaySections"
                  (click)="showData = !showData; showMenu = false"
                  class="w-full text-left px-3 py-2 text-xs hover:bg-gray-50 flex items-center justify-between">
             View Data
             <lucide-icon *ngIf="showData" name="check" class="w-3 h-3"></lucide-icon>
          </button>
          <button *ngIf="message.sql"
                  (click)="showSql = !showSql; showMenu = false"
                  class="w-full text-left px-3 py-2 text-xs hover:bg-gray-50 flex items-center justify-between">
             View SQL
             <lucide-icon *ngIf="showSql" name="check" class="w-3 h-3"></lucide-icon>
          </button>
        </div>
      </div>
    </div>

    <!-- Data and SQL Panels (moved ABOVE summary) -->
    <app-data-table *ngIf="showData && message.data"
      [data]="message.data" [numericColumns]="message.chartSpec?.columns?.numeric || []"></app-data-table>

    <ng-container *ngIf="showData && message.displaySections">
      <div *ngFor="let section of message.displaySections" class="mb-3">
        <div class="text-xs font-medium text-gray-500 mb-1">{{ section.label }}</div>
        <app-data-table [data]="section.data" [numericColumns]="[]"></app-data-table>
      </div>
    </ng-container>

    <app-sql-panel *ngIf="showSql && message.sql" [sql]="message.sql" class="mb-3 block"></app-sql-panel>

    <!-- Streaming summary text -->
    <p *ngIf="message.content"
       class="text-sm text-gray-800 leading-relaxed mb-3 whitespace-pre-wrap">
      {{ message.content }}
    </p>



    <!-- Cross conversation references -->
    <div *ngIf="message.crossConversationRefs?.length" class="flex flex-wrap gap-2 mb-3">
      <span class="text-xs text-gray-400 mt-0.5">📂 Found in:</span>
      <a *ngFor="let ref of message.crossConversationRefs"
         (click)="chat.selectConversation(ref.conversation_id)"
         class="text-xs text-brand-primary underline cursor-pointer hover:text-brand-navy transition-colors">
        {{ ref.title }}
      </a>
    </div>

    <!-- Panel toggle buttons -->
    <div *ngIf="message.status === 'complete' && message.chartSpec && !message.chartSpec.single_value && message.chartSpec.recommendations.length > 1" class="flex flex-wrap gap-2 mb-3">
      <button (click)="showChart = !showChart"
              class="flex items-center gap-1 border border-gray-200 rounded-full px-3 py-1 text-xs
                     hover:border-brand-primary hover:text-brand-primary transition">
        <lucide-icon name="bar-chart-2" class="w-3.5 h-3.5"></lucide-icon> Chart {{ showChart ? '▴' : '▾' }}
      </button>
    </div>

    <!-- Visualization panels -->
    <ng-container *ngIf="message.chartSpec as spec">
      <div *ngIf="spec.single_value" class="text-center py-6 border border-gray-100 bg-white rounded-xl shadow-sm mb-3">
        <div class="text-4xl font-bold text-brand-navy">{{ message.data?.[0]?.[spec.columns.numeric[0] || ''] }}</div>
        <div class="text-sm text-gray-500 mt-1 uppercase tracking-wider">{{ spec.columns.numeric[0] || '' | titlecase }}</div>
      </div>
    </ng-container>

    <app-chart-selector *ngIf="showChart && message.chartSpec && !message.chartSpec.single_value && message.chartSpec.recommendations.length > 1 && message.data"
      [spec]="message.chartSpec" [data]="message.data"></app-chart-selector>

    <!-- Follow-up chips -->
    <div *ngIf="message.followups?.length" class="mt-4">
      <div class="flex items-center gap-1 text-xs text-gray-400 mb-2 font-medium">
        <lucide-icon name="lightbulb" class="w-3.5 h-3.5"></lucide-icon> Try:
      </div>
      <div class="flex flex-col items-start gap-2">
        <button *ngFor="let f of message.followups"
                (click)="followupClick.emit(f)"
                class="text-left text-xs bg-brand-surface text-brand-navy border border-brand-primary/20
                       rounded-full px-3 py-1.5 hover:bg-brand-primary/10 transition">
          {{ f }}
        </button>
      </div>
    </div>

    <!-- Error state -->
    <p *ngIf="message.status === 'error'"
       class="text-red-500 text-sm bg-red-50 border border-red-100 rounded-lg px-3 py-2 mt-2">
      {{ message.content }}
    </p>
  </div>
</div>
