// frontend-angular/src/app/features/chat/chart-selector/chart-selector.component.ts
import { Component, Input, OnInit, OnChanges, SimpleChanges } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { ChartSpec, ChartType } from '../../../shared/models/chat.model';
import { ChartRendererComponent } from '../chart-renderer/chart-renderer.component';
import { DataTableComponent } from '../data-table/data-table.component';
import { LucideAngularModule, BarChart2, PieChart, LineChart, ScatterChart } from 'lucide-angular';

@Component({
  selector: 'app-chart-selector',
  standalone: true,
  imports: [
    CommonModule, 
    FormsModule, 
    ChartRendererComponent,
    DataTableComponent,
    LucideAngularModule
  ],
  templateUrl: './chart-selector.component.html',
})
export class ChartSelectorComponent implements OnInit, OnChanges {
  @Input() spec!: ChartSpec;
  @Input() data!: Record<string, unknown>[];

  activeType!: ChartType;
  xCol = '';
  yCol = '';
  sortXAs?: string;

  ngOnInit() {
    this.initSelections();
  }

  ngOnChanges(changes: SimpleChanges) {
    if (changes['spec'] && !changes['spec'].firstChange) {
      this.initSelections();
    }
  }

  private initSelections() {
    if (!this.spec) return;
    this.activeType = this.spec.active;
    const rec = this.spec.recommendations.find(r => r.type === this.activeType);
    this.xCol = rec?.x || this.spec.columns.dimensions?.[0] || this.spec.columns.categorical?.[0] || '';
    this.yCol = rec?.y || this.spec.columns.measures?.[0] || this.spec.columns.numeric?.[0] || '';
    this.sortXAs = rec?.sort_x_as;
  }

  selectType(type: ChartType) {
    this.activeType = type;
    const rec = this.spec.recommendations.find(r => r.type === type);
    if (rec) { 
      this.xCol = rec.x || this.xCol; 
      this.yCol = rec.y || this.yCol; 
      this.sortXAs = rec.sort_x_as;
    }
  }

  get xAxisOptions(): string[] {
    if (!this.spec || !this.spec.columns) return [];
    return this.spec.columns.dimensions || this.spec.columns.categorical || [];
  }

  get yAxisOptions(): string[] {
    if (!this.spec || !this.spec.columns) return [];
    return this.spec.columns.measures || this.spec.columns.numeric || [];
  }
}

<div class="border border-gray-200 rounded-xl p-4 mt-2 bg-white" *ngIf="spec.recommendations.length > 1">
  <div class="text-sm font-medium text-gray-700 mb-3">Visualization</div>
  <p *ngIf="spec.fallback_reason" class="text-xs text-amber-600 mb-2">ℹ️ {{ spec.fallback_reason }}</p>

  <div class="flex flex-wrap gap-2 mb-3 border-b border-gray-100 pb-2">
    <button *ngFor="let r of spec.recommendations"
            (click)="selectType(r.type)"
            [class.text-brand-primary]="activeType === r.type"
            [class.border-brand-primary]="activeType === r.type"
            class="flex items-center gap-1.5 text-xs px-3 py-1.5 rounded-full border border-transparent hover:bg-brand-surface transition font-medium">
      <lucide-icon [name]="r.icon" class="w-4 h-4"></lucide-icon> {{ r.label }}
    </button>
  </div>

  <div *ngIf="activeType !== 'table'" class="flex flex-wrap gap-3 mb-3 text-xs">
    <label class="flex items-center gap-1.5 text-gray-600">
      X-Axis:
      <select [(ngModel)]="xCol" class="border border-gray-200 rounded px-2 py-1 outline-none focus:border-brand-primary bg-white">
        <option *ngFor="let c of xAxisOptions" [value]="c">{{ c }}</option>
      </select>
    </label>
    <label class="flex items-center gap-1.5 text-gray-600" *ngIf="activeType !== 'pie'">
      Y-Axis:
      <select [(ngModel)]="yCol" class="border border-gray-200 rounded px-2 py-1 outline-none focus:border-brand-primary bg-white">
        <option *ngFor="let c of yAxisOptions" [value]="c">{{ c }}</option>
      </select>
    </label>
  </div>

  <app-chart-renderer
    *ngIf="activeType !== 'table'"
    [type]="activeType"
    [data]="data"
    [xCol]="xCol"
    [yCol]="yCol"
    [sortXAs]="sortXAs"
  ></app-chart-renderer>
</div>

<app-data-table *ngIf="spec.recommendations.length === 1 && spec.active === 'table'"
                [data]="data" [numericColumns]="spec.columns.measures || spec.columns.numeric || []"></app-data-table>

// frontend/src/components/visualization/ChartSelector.tsx
import { BarChart2, PieChart, LineChart, ScatterChart, Table2 } from 'lucide-react'
import { ChartSpec } from '@/types/chat'

const ICONS: Record<string, any> = {
  BarChart2,
  PieChart,
  LineChart,
  ScatterChart,
  Table2,
}

interface Props {
  spec: ChartSpec
  onSpecChange: (spec: ChartSpec) => void
}

export default function ChartSelector({ spec, onSpecChange }: Props) {
  // Safe defaults if columns is undefined
  const allColumns = [
    ...(spec.columns?.categorical || []),
    ...(spec.columns?.numeric || []),
    ...(spec.columns?.date || [])
  ]

  return (
    <div className="flex flex-col gap-4 mb-4">
      <div className="flex border-b border-gray-200">
        {spec.recommendations.map((rec) => {
          const Icon = ICONS[rec.icon] || BarChart2
          const isActive = spec.active === rec.type
          return (
            <button
              key={rec.type}
              onClick={() => {
                onSpecChange({
                  ...spec,
                  active: rec.type,
                  recommendations: spec.recommendations.map(r =>
                    r.type === rec.type ? { ...r, active: true } : r
                  ),
                })
              }}
              className={`flex items-center gap-2 px-4 py-2 text-sm font-medium border-b-2 transition-colors ${
                isActive
                  ? 'border-brand-primary text-brand-primary'
                  : 'border-transparent text-gray-500 hover:text-gray-700 hover:border-gray-300'
              }`}
            >
              <Icon className="w-4 h-4" />
              {rec.label}
            </button>
          )
        })}
      </div>

      {spec.active !== 'table' && spec.columns && (
        <div className="flex gap-4 items-center text-sm">
          <div className="flex items-center gap-2">
            <span className="text-gray-600">X-Axis:</span>
            <select
              className="border border-gray-300 rounded px-2 py-1 text-sm bg-white"
              value={spec.recommendations.find(r => r.type === spec.active)?.x || ''}
              onChange={(e) => {
                onSpecChange({
                  ...spec,
                  recommendations: spec.recommendations.map(r =>
                    r.type === spec.active ? { ...r, x: e.target.value } : r
                  )
                })
              }}
            >
              <option value="">Select...</option>
              {allColumns.map(c => <option key={c} value={c}>{c}</option>)}
            </select>
          </div>
          <div className="flex items-center gap-2">
            <span className="text-gray-600">Y-Axis:</span>
            <select
              className="border border-gray-300 rounded px-2 py-1 text-sm bg-white"
              value={spec.recommendations.find(r => r.type === spec.active)?.y || ''}
              onChange={(e) => {
                onSpecChange({
                  ...spec,
                  recommendations: spec.recommendations.map(r =>
                    r.type === spec.active ? { ...r, y: e.target.value } : r
                  )
                })
              }}
            >
              <option value="">Select...</option>
              {allColumns.map(c => <option key={c} value={c}>{c}</option>)}
            </select>
          </div>
        </div>
      )}
    </div>
  )
}
