// frontend-angular/src/app/features/chat/data-table/data-table.component.ts
import { Component, Input, OnInit } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';

@Component({
  selector: 'app-data-table',
  standalone: true,
  imports: [CommonModule, FormsModule],
  templateUrl: './data-table.component.html',
})
export class DataTableComponent implements OnInit {
  @Input() data!: Record<string, unknown>[];
  @Input() numericColumns: string[] = [];

  columns: string[] = [];
  search = '';
  sortCol = '';
  sortDir: 'asc' | 'desc' = 'asc';
  page = 1;
  pageSize = 25;

  ngOnInit() {
    this.columns = this.data && this.data.length ? Object.keys(this.data[0]) : [];
  }

  get filtered(): Record<string, unknown>[] {
    if (!this.data) return [];
    let rows = this.data;
    if (this.search) {
      const q = this.search.toLowerCase();
      rows = rows.filter(r => Object.values(r).some(v => String(v).toLowerCase().includes(q)));
    }
    if (this.sortCol) {
      rows = [...rows].sort((a, b) => {
        const av = a[this.sortCol], bv = b[this.sortCol];
        const cmp = av! < bv! ? -1 : av! > bv! ? 1 : 0;
        return this.sortDir === 'asc' ? cmp : -cmp;
      });
    }
    return rows;
  }

  get paged(): Record<string, unknown>[] {
    const start = (this.page - 1) * this.pageSize;
    return this.filtered.slice(start, start + this.pageSize);
  }

  get totalPages(): number {
    return Math.max(1, Math.ceil(this.filtered.length / this.pageSize));
  }

  sort(col: string) {
    if (this.sortCol === col) {
      this.sortDir = this.sortDir === 'asc' ? 'desc' : 'asc';
    } else {
      this.sortCol = col;
      this.sortDir = 'asc';
    }
  }

  isNumeric(col: string): boolean {
    return this.numericColumns.includes(col);
  }
}

<div class="border border-gray-200 rounded-xl mt-2 overflow-hidden">
  <div class="flex items-center justify-between p-3 border-b border-gray-100">
    <span class="text-sm font-medium">📋 Results · {{ filtered.length }} rows</span>
    <input [(ngModel)]="search" placeholder="🔍 Search..."
           class="text-xs border border-gray-200 rounded px-2 py-1 w-40" />
  </div>

  <div class="overflow-x-auto max-h-80 overflow-y-auto">
    <table class="w-full text-xs">
      <thead class="sticky top-0 bg-white">
        <tr>
          <th *ngFor="let col of columns"
              (click)="sort(col)"
              [class.text-right]="isNumeric(col)"
              class="px-3 py-2 font-medium text-gray-500 cursor-pointer hover:text-brand-primary border-b border-gray-100">
            {{ col }} <span class="text-gray-300">↕</span>
          </th>
        </tr>
      </thead>
      <tbody>
        <tr *ngFor="let row of paged; let i = index"
            [class.bg-brand-surface]="i % 2 === 1">
          <td *ngFor="let col of columns"
              [class.text-right]="isNumeric(col)"
              class="px-3 py-1.5 border-b border-gray-50">
            {{ row[col] }}
          </td>
        </tr>
      </tbody>
    </table>
  </div>

  <div class="flex items-center justify-between p-2 text-xs text-gray-500 border-t border-gray-100">
    <button (click)="page = page - 1" [disabled]="page <= 1" class="disabled:opacity-30">← Prev</button>
    <span>Page {{ page }} of {{ totalPages }}</span>
    <button (click)="page = page + 1" [disabled]="page >= totalPages" class="disabled:opacity-30">Next →</button>
  </div>
</div>

// frontend/src/components/visualization/DataTable.tsx
import { useState, useMemo } from 'react'
import { ArrowUpDown, Search } from 'lucide-react'

interface Props {
  data: Record<string, any>[]
}

export default function DataTable({ data }: Props) {
  const [sortCol, setSortCol] = useState<string | null>(null)
  const [sortDesc, setSortDesc] = useState(false)
  const [search, setSearch] = useState('')
  const [page, setPage] = useState(0)
  const ROWS_PER_PAGE = 25

  const columns = useMemo(() => {
    if (!data || data.length === 0) return []
    return Object.keys(data[0])
  }, [data])

  const filteredAndSortedData = useMemo(() => {
    if (!data) return []
    let result = [...data]
    
    // Filter
    if (search) {
      const q = search.toLowerCase()
      result = result.filter(row => 
        Object.values(row).some(val => String(val).toLowerCase().includes(q))
      )
    }

    // Sort
    if (sortCol) {
      result.sort((a, b) => {
        const valA = a[sortCol]
        const valB = b[sortCol]
        if (valA === valB) return 0
        if (valA === null || valA === undefined) return sortDesc ? 1 : -1
        if (valB === null || valB === undefined) return sortDesc ? -1 : 1
        
        if (typeof valA === 'number' && typeof valB === 'number') {
          return sortDesc ? valB - valA : valA - valB
        }
        return sortDesc 
          ? String(valB).localeCompare(String(valA)) 
          : String(valA).localeCompare(String(valB))
      })
    }
    
    return result
  }, [data, search, sortCol, sortDesc])

  const totalPages = Math.ceil(filteredAndSortedData.length / ROWS_PER_PAGE)
  const currentData = filteredAndSortedData.slice(page * ROWS_PER_PAGE, (page + 1) * ROWS_PER_PAGE)

  const handleSort = (col: string) => {
    if (sortCol === col) {
      if (sortDesc) {
        setSortCol(null)
      } else {
        setSortDesc(true)
      }
    } else {
      setSortCol(col)
      setSortDesc(false)
    }
  }

  if (!data || data.length === 0) {
    return <div className="p-4 text-sm text-gray-500">No data available</div>
  }

  return (
    <div className="flex flex-col gap-4">
      <div className="flex justify-between items-center">
        <div className="text-sm font-medium text-gray-700">
          📋 Results <span className="bg-gray-100 px-2 py-0.5 rounded text-gray-600 ml-2">{filteredAndSortedData.length} rows</span>
        </div>
        <div className="relative">
          <Search className="absolute left-2.5 top-2 h-4 w-4 text-gray-400" />
          <input
            type="text"
            placeholder="Search..."
            value={search}
            onChange={(e) => { setSearch(e.target.value); setPage(0); }}
            className="pl-9 pr-4 py-1.5 border border-gray-300 rounded-md text-sm focus:outline-none focus:ring-1 focus:ring-brand-primary w-64"
          />
        </div>
      </div>

      <div className="border border-gray-200 rounded-lg overflow-hidden">
        <div className="overflow-x-auto max-h-[500px]">
          <table className="w-full text-sm text-left">
            <thead className="text-xs text-gray-700 uppercase bg-gray-50 sticky top-0 shadow-sm z-10">
              <tr>
                {columns.map(col => (
                  <th 
                    key={col} 
                    className="px-4 py-3 cursor-pointer hover:bg-gray-100 whitespace-nowrap"
                    onClick={() => handleSort(col)}
                  >
                    <div className="flex items-center gap-1">
                      {col}
                      <ArrowUpDown className={`h-3 w-3 ${sortCol === col ? 'text-brand-primary' : 'text-gray-400'}`} />
                    </div>
                  </th>
                ))}
              </tr>
            </thead>
            <tbody>
              {currentData.map((row, i) => (
                <tr key={i} className={`border-b border-gray-100 ${i % 2 === 1 ? 'bg-[#F0FDFB]' : 'bg-white'} hover:bg-gray-50`}>
                  {columns.map(col => (
                    <td key={col} className={`px-4 py-2 ${typeof row[col] === 'number' ? 'text-right' : ''}`}>
                      {row[col] !== null ? String(row[col]) : <span className="text-gray-400 italic">null</span>}
                    </td>
                  ))}
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      </div>

      {totalPages > 1 && (
        <div className="flex justify-between items-center text-sm text-gray-600 bg-gray-50 p-2 rounded border border-gray-200">
          <button 
            onClick={() => setPage(p => Math.max(0, p - 1))}
            disabled={page === 0}
            className="px-3 py-1 bg-white border border-gray-300 rounded disabled:opacity-50"
          >
            ← Prev
          </button>
          <span>Page {page + 1} of {totalPages}</span>
          <button 
            onClick={() => setPage(p => Math.min(totalPages - 1, p + 1))}
            disabled={page === totalPages - 1}
            className="px-3 py-1 bg-white border border-gray-300 rounded disabled:opacity-50"
          >
            Next →
          </button>
        </div>
      )}
    </div>
  )
}
