// frontend/src/components/visualization/ChartRenderer.tsx
import dynamic from 'next/dynamic'
import { ChartSpec } from '@/types/chat'
import DataTable from './DataTable'

// Plotly must be loaded dynamically because it requires the window object
const Plot = dynamic(() => import('react-plotly.js'), { ssr: false })

const BRAND_COLORS = ['#28A5A0', '#2C3687', '#61DAD3', '#4A5FAF', '#8BC4C1', '#6B7EC4']

const BASE_LAYOUT = {
  paper_bgcolor: 'rgba(0,0,0,0)',
  plot_bgcolor: 'rgba(0,0,0,0)',
  font: { family: 'Inter, sans-serif', color: '#1A1A2E', size: 12 },
  margin: { t: 40, r: 20, b: 60, l: 60 },
  height: 380,
  showlegend: true,
  legend: { orientation: 'h' as const, y: -0.25 },
  colorway: BRAND_COLORS,
}

interface Props {
  spec: ChartSpec
  data: Record<string, any>[]
}

export default function ChartRenderer({ spec, data }: Props) {
  if (!data || data.length === 0) return null

  // If table is active, render the DataTable instead of Plotly
  if (spec.active === 'table') {
    return <DataTable data={data} />
  }

  // Get active recommendation settings
  const activeRec = spec.recommendations.find(r => r.type === spec.active)
  const xCol = activeRec?.x || (spec.columns?.categorical?.[0] || Object.keys(data[0])[0])
  const yCol = activeRec?.y || (spec.columns?.numeric?.[0] || Object.keys(data[0])[0])

  const xData = data.map(d => d[xCol])
  const yData = data.map(d => d[yCol])

  let plotData: any[] = []
  let layout = { ...BASE_LAYOUT, title: `${yCol} by ${xCol}` }

  switch (spec.active) {
    case 'bar':
      // Horizontal if > 12 categories
      const isHorizontal = new Set(xData).size > 12
      plotData = [{
        type: 'bar',
        x: isHorizontal ? yData : xData,
        y: isHorizontal ? xData : yData,
        orientation: isHorizontal ? 'h' : 'v',
        marker: { color: BRAND_COLORS[0] }
      }]
      if (isHorizontal) {
        layout.margin.l = 120 // more room for y-axis labels
      }
      break

    case 'pie':
      // Aggregate for pie chart if there are many categories
      const counts: Record<string, number> = {}
      data.forEach(d => {
        const key = String(d[xCol])
        counts[key] = (counts[key] || 0) + Number(d[yCol] || 1)
      })
      
      const sortedKeys = Object.keys(counts).sort((a, b) => counts[b] - counts[a])
      const topKeys = sortedKeys.slice(0, 10)
      const otherValue = sortedKeys.slice(10).reduce((sum, key) => sum + counts[key], 0)
      
      const labels = [...topKeys]
      const values = topKeys.map(k => counts[k])
      
      if (otherValue > 0) {
        labels.push('Other')
        values.push(otherValue)
      }

      plotData = [{
        type: 'pie',
        labels: labels,
        values: values,
        hole: 0.4,
        marker: { colors: BRAND_COLORS }
      }]
      break

    case 'line':
      // Sort by X-axis (usually time)
      const sortedData = [...data].sort((a, b) => {
        const valA = a[xCol]
        const valB = b[xCol]
        if (valA === null) return 1
        if (valB === null) return -1
        return String(valA).localeCompare(String(valB))
      })
      plotData = [{
        type: 'scatter',
        mode: 'lines+markers',
        x: sortedData.map(d => d[xCol]),
        y: sortedData.map(d => d[yCol]),
        line: { color: BRAND_COLORS[0], width: 2 },
        marker: { size: 6 }
      }]
      break

    case 'scatter':
      // Optional color by category
      const colorCol = spec.columns?.categorical?.find(c => c !== xCol && c !== yCol)
      
      if (colorCol) {
        const categories = Array.from(new Set(data.map(d => d[colorCol])))
        plotData = categories.map((cat, i) => ({
          type: 'scatter',
          mode: 'markers',
          name: String(cat),
          x: data.filter(d => d[colorCol] === cat).map(d => d[xCol]),
          y: data.filter(d => d[colorCol] === cat).map(d => d[yCol]),
          marker: { color: BRAND_COLORS[i % BRAND_COLORS.length], size: 8 }
        }))
      } else {
        plotData = [{
          type: 'scatter',
          mode: 'markers',
          x: xData,
          y: yData,
          marker: { color: BRAND_COLORS[0], size: 8 }
        }]
      }
      break
      
    default:
      return <div className="p-4 text-red-500">Unsupported chart type: {spec.active}</div>
  }

  return (
    <div className="w-full bg-white rounded-lg border border-gray-200 overflow-hidden">
      <Plot
        data={plotData}
        layout={layout}
        useResizeHandler={true}
        style={{ width: '100%', height: '100%' }}
        config={{ displayModeBar: false, responsive: true }}
      />
    </div>
  )
}

// frontend-angular/src/app/features/chat/chart-renderer/chart-renderer.component.ts
import { Component, Input, OnChanges } from '@angular/core';
import { CommonModule } from '@angular/common';
import { PlotlyModule } from 'angular-plotly.js';
import { ChartType } from '../../../shared/models/chat.model';

const BRAND_COLORS = ['#28A5A0', '#2C3687', '#61DAD3', '#4A5FAF', '#8BC4C1', '#6B7EC4'];

const BASE_LAYOUT: any = {
  paper_bgcolor: 'rgba(0,0,0,0)',
  plot_bgcolor:  'rgba(0,0,0,0)',
  font: { family: 'Inter, sans-serif', color: '#1A1A2E', size: 12 },
  margin: { t: 40, r: 20, b: 60, l: 60 },
  height: 380,
  showlegend: true,
  legend: { orientation: 'h', y: -0.25 },
  colorway: BRAND_COLORS,
};

@Component({
  selector: 'app-chart-renderer',
  standalone: true,
  imports: [CommonModule, PlotlyModule],
  template: `<plotly-plot [data]="plotData" [layout]="layout" [config]="{responsive: true, displaylogo: false}"></plotly-plot>`,
})
export class ChartRendererComponent implements OnChanges {
  @Input() type!: ChartType;
  @Input() data!: Record<string, unknown>[];
  @Input() xCol!: string;
  @Input() yCol!: string;

  plotData: any[] = [];
  layout = BASE_LAYOUT;

  ngOnChanges() {
    if (!this.data || !this.data.length || !this.xCol || (!this.yCol && this.type !== 'pie')) {
      return;
    }
    this.plotData = this.buildTrace();
  }

  private buildTrace(): any[] {
    const x = this.data.map(d => d[this.xCol]);
    const y = this.data.map(d => d[this.yCol]);

    switch (this.type) {
      case 'bar': {
        const horizontal = new Set(x).size > 12;
        return [{
          type: 'bar',
          x: horizontal ? y : x,
          y: horizontal ? x : y,
          orientation: horizontal ? 'h' : 'v',
          marker: { color: BRAND_COLORS[0] },
        }];
      }
      case 'pie': {
        const top10 = this.topNWithOther(10);
        return [{ type: 'pie', labels: top10.labels, values: top10.values, hole: 0.4 }];
      }
      case 'line': {
        const sorted = [...this.data].sort((a, b) =>
          String(a[this.xCol]).localeCompare(String(b[this.xCol])));
        return [{
          type: 'scatter', mode: 'lines+markers',
          x: sorted.map(d => d[this.xCol]),
          y: sorted.map(d => d[this.yCol]),
          line: { color: BRAND_COLORS[0] },
        }];
      }
      case 'scatter':
        return [{ type: 'scatter', mode: 'markers', x, y, marker: { color: BRAND_COLORS[1] } }];
      default:
        return [];
    }
  }

  private topNWithOther(n: number): { labels: any[]; values: any[] } {
    // If yCol is not defined for pie, fallback or return empty
    if (!this.yCol) {
      // In pie charts, sometimes only xCol (category) is needed if we just count them
      // But the spec assumes yCol has the metric. If no yCol, let's just count frequencies of xCol
      const counts: Record<string, number> = {};
      for (const d of this.data) {
        const val = String(d[this.xCol]);
        counts[val] = (counts[val] || 0) + 1;
      }
      const sortedFreq = Object.entries(counts).sort((a, b) => b[1] - a[1]);
      const topFreq = sortedFreq.slice(0, n);
      const restFreq = sortedFreq.slice(n);
      const otherSumFreq = restFreq.reduce((s, [_, v]) => s + v, 0);
      const labelsFreq = topFreq.map(d => d[0]);
      const valuesFreq = topFreq.map(d => d[1]);
      if (restFreq.length) { labelsFreq.push('Other'); valuesFreq.push(otherSumFreq); }
      return { labels: labelsFreq, values: valuesFreq };
    }

    const sorted = [...this.data].sort((a, b) => Number(b[this.yCol]) - Number(a[this.yCol]));
    const top = sorted.slice(0, n);
    const rest = sorted.slice(n);
    const otherSum = rest.reduce((s, d) => s + Number(d[this.yCol] || 0), 0);
    const labels = top.map(d => d[this.xCol]);
    const values = top.map(d => Number(d[this.yCol]));
    if (rest.length) { labels.push('Other'); values.push(otherSum); }
    return { labels, values };
  }
}

<div *ngIf="!hasValidData" class="text-center py-12 text-gray-400 text-sm">
  📊 Not enough variation in the data to draw a meaningful {{ type }} chart.
  <br/>Try the Data Table view instead.
</div>
<plotly-plot *ngIf="hasValidData" [data]="plotData" [layout]="layout" [config]="{responsive: true, displaylogo: false}"></plotly-plot>
